const REQUEST_ACCOUNT_ACTION = "REQUEST_ACCOUNT_ACTION"
const REQUEST_ACCOUNT_SAGA = "REQUEST_ACCOUNT_SAGA"
const FETCH_GREETING_ACTION = "FETCH_GREETING_ACTION"
const FETCH_GREETING_SAGA = "FETCH_GREETING_SAGA"
const GET_BALANCE_ACTION = "GET_BALANCE_ACTION"
const GET_BALANCE_SAGA = "GET_BALANCE_SAGA"
const SET_GREETING_ACTION = "SET_GREETING_ACTION"
const SET_GREETING_SAGA = "SET_GREETING_SAGA"
const SEND_COINS_ACTION = "SEND_COINS_ACTION"
const SEND_COINS_SAGA = "SEND_COINS_SAGA"

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  REQUEST_ACCOUNT_ACTION,
  REQUEST_ACCOUNT_SAGA,
  FETCH_GREETING_ACTION,
  FETCH_GREETING_SAGA,
  GET_BALANCE_ACTION,
  GET_BALANCE_SAGA,
  SET_GREETING_ACTION,
  SET_GREETING_SAGA,
  SEND_COINS_ACTION,
  SEND_COINS_SAGA,
}
